
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftOPMULleftOPADDNUMBER OPADD OPMULexpression : NUMBERexpression : expression OPADD expressionexpression : expression OPMUL expression'
    
_lr_action_items = {'NUMBER':([0,3,4,],[2,2,2,]),'$end':([1,2,5,6,],[0,-1,-2,-3,]),'OPADD':([1,2,5,6,],[3,-1,-2,3,]),'OPMUL':([1,2,5,6,],[4,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,],[1,5,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> NUMBER','expression',1,'p_expression_num','myparser.py',7),
  ('expression -> expression OPADD expression','expression',3,'p_expression_add','myparser.py',13),
  ('expression -> expression OPMUL expression','expression',3,'p_expression_mul','myparser.py',22),
]
